services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.local.conf:/etc/nginx/conf.d/default.conf:ro
      - ../personal-website/frontend:/srv/personal-website:ro
    networks:
      - reverse-proxy
    restart: "no"

networks:
  reverse-proxy:
    name: reverse-proxy
