services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../personal-website/frontend:/srv:ro
      - certbot_data:/var/www/certbot:ro
      - certbot_config:/etc/letsencrypt:ro
    networks:
      - reverse-proxy
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - certbot_data:/var/www/certbot
      - certbot_config:/etc/letsencrypt
    networks:
      - reverse-proxy

volumes:
  certbot_data:
    name: reverse-proxy_certbot_data
  certbot_config:
    name: reverse-proxy-certbot-config

networks:
  reverse-proxy:
    name: reverse-proxy
