server {
    listen 80;
    server_name fruitshop.lucachioni.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://fruitshop.lucachioni.com$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name fruitshop.lucachioni.com;

    ssl_certificate /etc/letsencrypt/live/fruitshop.lucachioni.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/fruitshop.lucachioni.com/privkey.pem;

    location / {
        proxy_pass http://fruit-shop:80;
        include /etc/nginx/snippets/proxy-headers.conf;
    }
}
