server {
    listen 80;
    server_name lucachioni.com www.lucachioni.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://lucachioni.com$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name www.lucachioni.com;

    ssl_certificate /etc/letsencrypt/live/lucachioni.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lucachioni.com/privkey.pem;

    return 301 https://lucachioni.com$request_uri;
}

server {
    listen 443 ssl;
    server_name lucachioni.com;

    ssl_certificate /etc/letsencrypt/live/lucachioni.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lucachioni.com/privkey.pem;

    root /srv/personal-website;
    index index.html;

    location /api/ {
        proxy_pass http://personal-website-backend:8000;
        include /etc/nginx/snippets/proxy-headers.conf;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /error.html;

    location = /error.html {
        internal;
    }
}
