server {
    listen 80;
    server_name shop.lucachioni.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        proxy_pass http://fruit-shop:80;
        include /etc/nginx/snippets/proxy-headers.conf;
    }
}
